### ISSUE TITLE
Your code doesnt work

### ISSUE THREAD

**Issue by mrkdevelopment** [laraloop/ui#1]
I ran an install and get this:

include(F:\laragon\www\ubuturo-vapor\vendor\composer/../laraloop/ui/src/UiServiceProvider.php): failed to open stream: No such file or directory

**Comment by thewebartisan7** [comment]
Did you run `composer install` before?

**Comment by mrkdevelopment** [comment]
yes. Composer install and composer update with a dump auto load. No dice

**Comment by thewebartisan7** [comment]
Strange.

Can you see the folder vendor/laraloop/ui symlinked ?

**Comment by mrkdevelopment** [comment]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 11 installs, 0 updates, 0 removals
  - Installing league/oauth1-client (v1.8.2): Loading from cache
  - Installing laravel/socialite (v5.0.1): Loading from cache
  - Installing paragonie/constant_time_encoding (v2.3.0): Loading from cache
  - Installing pragmarx/google2fa (8.0.0): Loading from cache
  - Installing dasprid/enum (1.0.3): Loading from cache
  - Installing bacon/bacon-qr-code (2.0.2): Loading from cache
  - Installing jaybizzle/crawler-detect (v1.2.100): Loading from cache
  - Installing mobiledetect/mobiledetectlib (2.8.34): Loading from cache
  - Installing jenssegers/agent (v2.6.4): Loading from cache
  - Installing laravel/fortify (v1.6.1): Loading from cache
  - Installing laraloop/ui (dev-master): Source already present
bacon/bacon-qr-code suggests installing ext-imagick (to generate QR code images)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: jenssegers/agent
Discovered Package: laraloop/ui
Discovered Package: laravel/fortify
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
76 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by mrkdevelopment** [comment]
yes - ui library is symlinked

**Comment by thewebartisan7** [comment]
You have installed using quick installation package or in existing project?

**Comment by mrkdevelopment** [comment]
Yes

If I copy the UI folder over to vendor it starts working but its not using bootstrap which I selected. Its using UI Kit if I do that

**Comment by mrkdevelopment** [comment]
So the install doesnt work - like my ticket in code canyon.

**Comment by thewebartisan7** [comment]
If copying directory packages/laraloop/ui to vendor/laraloop/ui fixed, then something is wrong with symlink.

In composer.json there is how package is loaded:

```
    "repositories": [{
        "type": "path",
        "url": "packages/*/*/",
        "options": {
            "symlink": true
        }
    }],
```

I can't test on windows, but I will investigate if I found something. In case there is also other way. Maybe just removing symlink: true.


Now, about second issue. You can easy switch framework via configuration

**Comment by thewebartisan7** [comment]
You can publish config in your root config/loop-ui.php and add:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Define framework UI
    |--------------------------------------------------------------------------
    |
    | Possible values are bootstrap|uikit
    |
    */
    'framework' => 'bootstrap',
]
```

**Comment by mrkdevelopment** [comment]
I removed the repo and symlink area because it didnt work. I ran laravel mix with a npm install and npm run production  - I still get UI kit

**Comment by thewebartisan7** [comment]
Did you run npm install / run production from package or from root ? In case from root, then you first need to publish assets source

**Comment by thewebartisan7** [comment]
Or you can also from package

```
cd packages/laraloop/ui
npm install && npm --framework=bootstrap run production
```

**Comment by thewebartisan7** [comment]
Notice options --framework

**Comment by thewebartisan7** [comment]
From root 

```
php artisan vendor:publish --tag=loop-ui-bootstrap-assets-src
```

Then add in your webpack.mix.js:

```
// Bootstrap
mix.js('resources/assets/bootstrap/js/app.js',  'public/assets/bootstrap/js/app.js');
mix.sass('assets/bootstrap/sass/app.scss', 'public/assets/bootstrap/css/app.css');

**Comment by thewebartisan7** [comment]
Follow this: https://github.com/laraloop/ui#compile-assets

**Comment by mrkdevelopment** [comment]
No - I ran the NPM from the vendor folder.

The config makes no difference. Yes - I tested the framework option already - that doesnt work either.

I also tried copy of the mix file - didnt work.

Ran the movement of mix to core and the php artisan vendor publish - doesnt work either.

In all cases did a ctrl + f5 and did a clear of cache. Doesnt work - still get UI Kit.

**Comment by mrkdevelopment** [comment]
Already followed the compile assets - doesnt work.

**Comment by thewebartisan7** [comment]
Did you change configuration?

Because bootstrap and uikit are already compiled in public folder.

Maybe you are compiling correctly, but didn't change in config.

**Comment by mrkdevelopment** [comment]
ERROR in multi ./resources/assets/bootstrap/js/app.js ./assets/bootstrap/sass/app.scss
Module not found: Error: Can't resolve '/mnt/f/laragon/www/ubuturo-vapor/assets/bootstrap/sass/app.scss' in '/mnt/f/laragon/www/ubuturo-vapor'
 @ multi ./resources/assets/bootstrap/js/app.js ./assets/bootstrap/sass/app.scss /assets/bootstrap/js/app[1]

ERROR in ./resources/assets/bootstrap/js/bootstrap.js
Module not found: Error: Can't resolve 'bootstrap' in '/mnt/f/laragon/www/ubuturo-vapor/resources/assets/bootstrap/js'
 @ ./resources/assets/bootstrap/js/bootstrap.js 4:19-39
 @ ./resources/assets/bootstrap/js/app.js
 @ multi ./resources/assets/bootstrap/js/app.js ./assets/bootstrap/sass/app.scss

ERROR in ./resources/assets/bootstrap/js/avatar.js
Module not found: Error: Can't resolve 'croppie' in '/mnt/f/laragon/www/ubuturo-vapor/resources/assets/bootstrap/js'
 @ ./resources/assets/bootstrap/js/avatar.js 8:0-30 47:24-31
 @ ./resources/assets/bootstrap/js/app.js
 @ multi ./resources/assets/bootstrap/js/app.js ./assets/bootstrap/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mrkwp/.npm/_logs/2020-10-16T12_22_07_882Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mrkwp/.npm/_logs/2020-10-16T12_22_07_899Z-debug.log

**Comment by thewebartisan7** [comment]
Can't even find bootstrap framework...

Please copy package.json from packages/laraloop/ui/package.json to your root, then run npm install

**Comment by mrkdevelopment** [comment]
It doesnt work. I already tried that. I actually copied all your dependancies from the package.json and ran that with an NPM Install and then I ran the npm run dev - didnt work

tried the npm framework thing - didnt work

ERROR in multi ./resources/assets/bootstrap/js/app.js ./assets/bootstrap/sass/app.scss
Module not found: Error: Can't resolve '/mnt/f/laragon/www/ubuturo-vapor/assets/bootstrap/sass/app.scss' in '/mnt/f/laragon/www/ubuturo-vapor'
 @ multi ./resources/assets/bootstrap/js/app.js ./assets/bootstrap/sass/app.scss /assets/bootstrap/js/app[1]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mrkwp/.npm/_logs/2020-10-16T12_27_22_409Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mrkwp/.npm/_logs/2020-10-16T12_27_22_432Z-debug.log

**Comment by thewebartisan7** [comment]
And sorry, your webpack.mix.js should be:


```

mix.js('resources/assets/bootstrap/js/app.js',  'public/assets/bootstrap/js/app.js');
mix.sass('resources/assets/bootstrap/sass/app.scss', 'public/assets/bootstrap/css/app.css');
```

Was missing "resources/"

**Comment by thewebartisan7** [comment]
I just tested and it works, after adding right path to app.scss

**Comment by thewebartisan7** [comment]
![Uploading Screenshot 2020-10-16 at 14.29.03.png…]()

**Comment by mrkdevelopment** [comment]
Nah
it doesnt because I now get Unable to locate Mix file: /assets/uikit/css/app.css. (View: F:\laragon\www\ubuturo-vapor\vendor\laraloop\ui\resources\views\uikit\layouts\master.blade.php)

**Comment by mrkdevelopment** [comment]
this is because the core UI kit in the views is still not picking up the config

**Comment by thewebartisan7** [comment]
<img width="988" alt="Screenshot 2020-10-16 at 14 29 03" src="https://user-images.githubusercontent.com/57477934/96258388-3efd7b80-0fbc-11eb-8dd4-5219fcf7545d.png">

**Comment by thewebartisan7** [comment]
Compilation should works with above webpack.mix.js

Regarding new issue with mix() check your public/manifest.json file, show me content

**Comment by mrkdevelopment** [comment]
yep - that is what I have

![image](https://user-images.githubusercontent.com/792400/96258526-dd62fe80-1007-11eb-93b5-9b9688470961.png)

**Comment by thewebartisan7** [comment]
Now, check your mix.sass()

Is wrong

**Comment by thewebartisan7** [comment]
is missing mix.sass("resources/..."

**Comment by mrkdevelopment** [comment]
![Uploading image.png…]()

**Comment by thewebartisan7** [comment]
Check my doc updated:

https://github.com/laraloop/ui/commit/c29865fa2f598043bc4403b1acc7f09634b1eada

**Comment by mrkdevelopment** [comment]
![Uploading image.png…]()

**Comment by mrkdevelopment** [comment]
![image](https://user-images.githubusercontent.com/792400/96258730-2c109880-1008-11eb-806e-2bb869e24ebd.png)

**Comment by mrkdevelopment** [comment]
![image](https://user-images.githubusercontent.com/792400/96258761-3b8fe180-1008-11eb-923e-162c299c3b47.png)

**Comment by mrkdevelopment** [comment]
![image](https://user-images.githubusercontent.com/792400/96258807-4ea2b180-1008-11eb-86bf-5538f1aad005.png)

**Comment by mrkdevelopment** [comment]
Still doesnt work.

**Comment by thewebartisan7** [comment]
Now delete public/manifest.json and run again npm run dev

**Comment by thewebartisan7** [comment]
I mean public/mix-manifest.json

**Comment by mrkdevelopment** [comment]
same result

**Comment by thewebartisan7** [comment]
Show me your public/mix-manifest.json

**Comment by mrkdevelopment** [comment]
your app is still loading UI kit in blade instead of the Bootstrap

![image](https://user-images.githubusercontent.com/792400/96258991-a2ad9600-1008-11eb-88b3-1a2707a7bf4e.png)

![image](https://user-images.githubusercontent.com/792400/96259016-accf9480-1008-11eb-9fbb-bdab1998ef13.png)

**Comment by thewebartisan7** [comment]
Now show me your configuration loop-ui.php in config/

**Comment by thewebartisan7** [comment]
You see in UiServiceProvider.php that views are loading according to config?

Code:

```
        $this->framework = $this->app->config['loop-ui']['framework'];
        $this->loadViewsFrom(__DIR__ . "/../resources/views/{$this->framework}", $this->framework);
```

**Comment by mrkdevelopment** [comment]
I already set that to have the boostrap name for framework variable.

**Comment by mrkdevelopment** [comment]
The do not load according to the config

![image](https://user-images.githubusercontent.com/792400/96259614-97a73580-1009-11eb-9b2c-26c948a6cac5.png)

**Comment by mrkdevelopment** [comment]
![image](https://user-images.githubusercontent.com/792400/96259721-bd343f00-1009-11eb-9306-9863930ad0de.png)

**Comment by mrkdevelopment** [comment]
![image](https://user-images.githubusercontent.com/792400/96259762-c8876a80-1009-11eb-8fa6-849db1db5ff3.png)

**Comment by mrkdevelopment** [comment]
Still not working.

**Comment by thewebartisan7** [comment]
Now seem work, is loading bootstrap. Before was most probably an issue with caching views of blade.

If happen again then you can run Laravel command `php artisan view:clear` and/or `php artisan cache:clear` 

Now you have again another issue which can be easy solved. Coming answer.

**Comment by mrkdevelopment** [comment]
same error - already ran the artisan commands. I still get the error

**Comment by thewebartisan7** [comment]
Open views/bootstrap/login.blade.php and change:

```
{{ _('Sign Up') }}
```

To:

```
{{ __('Sign Up') }}
```

**Comment by mrkdevelopment** [comment]
So after I register am I going to have to debug every screen like this? Its not good.

I know I'm the second purchaser but gee - simple testing bro. Make sure stuff works. having a double underscore error in a helper means you didn't test this screen in the deployed code.

**Comment by thewebartisan7** [comment]
It works fine on my system the single underscore, most probably in windows no.

I am testing code, don't worry. Is now all working fine?

**Comment by mrkdevelopment** [comment]
I need to test the rest of the interface. Have you tested with Teams turned on?

**Comment by thewebartisan7** [comment]
Teams is not included in Fortify. It would add a lot of more code and honestly I don't think it's useful for common project.

**Comment by thewebartisan7** [comment]
I have a private repo here in Github with some fix on Social. If you are happy with current code let me know and I will invite you to private Github. In case you are not, I can refund you no problem.

Please just consider to change your review in Envato.

Thank You.

**Comment by mrkdevelopment** [comment]
I will use a team function in my projects so it will be required for me. Im not sure the code is really of much use to me.

Ill probably spend more time editing it and wrangling it than making use of it ( which is the same for Jetstream - which is why I tried your plugin).

Do you do freelance stuff?

Wondering If I should hire you - if you are free to do that.

**Comment by thewebartisan7** [comment]
Yes I am available for custom work, you can write me via email laraloop.com@gmail.com

If there are more interest for team, I can add it.

**Comment by mrkdevelopment** [comment]
OK - thanks. I sent you an email.
